---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
  - echo -n "${DRONE_COMMIT}, latest" > .tags

- name: publish  
  image: plugins/docker
  settings:
    repo: meharabdullah/todo-app-k8s
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile

trigger:
  branch:
  - master